### 사용자 생성
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "qwer1234!@#$",
    "provider": "facebook",
    "name": "사용자명",
    "status": "active"
}


### 사용자 단건 조회
GET http://localhost:3000/api/v1/users/1
Content-Type: application/json


### 사용자 다건 조회
GET http://localhost:3000/api/v1/users?page=1&pageSize=15&orderField=email&orderBy=DESC
Content-Type: application/json


### 사용자 수정
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
    "id": 1,
    "password": "qwer1234!@#$",
    "provider": "email",
    "name": "사용자명",
    "status": "dormant"
}